services:
  - type: web
    name: dogenadocash
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DOGEOS_RPC_URL
        value: https://rpc.testnet.dogeos.com
      - key: SHIELDED_POOL_ADDRESS
        value: 0xc5F64faee07A6EFE235C12378101D62e370c0cD5

